### sing up
POST http://localhost:5000/auth/signUp
Content-Type: application/json

{
    "email": "moaad2@gmail.com",
    "password": 123456,
    "name" : "moaad"
}

### sign in

POST http://localhost:5000/auth/signIn
Content-Type: application/json

{
    "email" : "moaad2@gmail.com",
    "password": 123456
}

### projects

POST http://localhost:5000/projects
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjlkYjA3ZjJjMWRhMzEwZDAyYzViMjUiLCJpYXQiOjE2MDQxNjk4NTUsImV4cCI6MTYwNDI1NjI1NX0.oJqWcjqvw_fLtFB8di86yY-SZD-crJAjkr3AMKej52M

{
    "projectName": "Project 2"
}


###
GET  http://localhost:5000/projects
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjlkYjA3ZjJjMWRhMzEwZDAyYzViMjUiLCJpYXQiOjE2MDQxNjk4NTUsImV4cCI6MTYwNDI1NjI1NX0.oJqWcjqvw_fLtFB8di86yY-SZD-crJAjkr3AMKej52M

