const constants = {
    ADD_TASK_START: 'ADD_TASK_START',
    ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
    ADD_TASK_FAILURE: 'ADD_TASK_FAILURE',
    CREATE_PROJECT_START: 'CREATE_PROJECT_START',
    CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
    CREATE_PROJECT_FAILURE: 'CREATE_PROJECT_FAILURE',
    EDIT_PROJECT: 'EDIT_PROJECT',
    MOVE_CARD: 'MOVE_CARD',
    SET_PROJECTS: 'SET_PROJECTS',

    // auth actions
    SIGN_IN_USER_START : 'SIGN_IN_USER_START',
    SIGN_IN_USER_SUCCESS: 'SIGN_IN_USER_SUCCESS',
    SIGN_IN_USER_FAILURE: 'SIGN_IN_USER_FAILURE',
    
    SIGN_UP_USER_START : 'SIGN_UP_USER_START',
    SIGN_UP_USER_SUCCESS: 'SIGN_UP_USER_SUCCESS',
    SIGN_UP_USER_FAILURE: 'SIGN_UP_USER_FAILURE',
    LOG_USER_OUT: 'LOG_USER_OUT',

    // invite actions
    ADD_INVITE: 'ADD_INVITE',
    REMOVE_INVITE: 'REMOVE_INVITE',

    // MEMBERS
    ADD_MEMBER: 'ADD_MEMBER'

    
}

export default constants