const constants = {
    ADD_TASK: 'ADD_TASK',
    CREATE_PROJECT_START: 'CREATE_PROJECT_START',
    CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
    CREATE_PROJECT_FAILURE: 'CREATE_PROJECT_FAILURE',
    MOVE_CARD: 'MOVE_CARD',

    // auth actions
    SET_USER_START : 'SET_USER_START',
    SET_USER_SUCCESS: 'SET_USER_SUCCESS',
    SET_USER_FAILURE: 'SET_USER_FAILURE'
}

export default constants