const constants = {
    ADD_TASK: 'ADD_TASK',
    CREATE_PROJECT_START: 'CREATE_PROJECT_START',
    CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
    CREATE_PROJECT_FAILURE: 'CREATE_PROJECT_FAILURE',
    MOVE_CARD: 'MOVE_CARD',
    SET_PROJECTS: 'SET_PROJECTS',

    // auth actions
    SIGN_IN_USER_START : 'SIGN_IN_USER_START',
    SIGN_IN_USER_SUCCESS: 'SIGN_IN_USER_SUCCESS',
    SIGN_IN_USER_FAILURE: 'SIGN_IN_USER_FAILURE',
    
    SIGN_UP_USER_START : 'SIGN_UP_USER_START',
    SIGN_UP_USER_SUCCESS: 'SIGN_UP_USER_SUCCESS',
    SIGN_UP_USER_FAILURE: 'SIGN_UP_USER_FAILURE',
    LOG_USER_OUT: 'LOG_USER_OUT'
    
}

export default constants